# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: quickstart 0.8.2 ruby lib

Gem::Specification.new do |s|
  s.name = "quickstart"
  s.version = "0.8.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Chris Olstrom"]
  s.date = "2016-03-09"
  s.description = "Quickstart helps you start your next project, quickly."
  s.email = "chris@olstrom.com"
  s.executables = ["quickstart"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/quickstart",
    "doc/examples/gem/.document",
    "doc/examples/gem/.gitignore",
    "doc/examples/gem/.rspec",
    "doc/examples/gem/Gemfile",
    "doc/examples/gem/LICENSE",
    "doc/examples/gem/README.md",
    "doc/examples/gem/Rakefile",
    "doc/examples/gem/lib/__name__.rb",
    "doc/examples/gem/spec/__name___spec.rb",
    "doc/examples/gem/spec/spec_helper.rb",
    "lib/quickstart.rb",
    "lib/quickstart/cli.rb",
    "lib/quickstart/template.rb",
    "quickstart.gemspec",
    "spec/quickstart_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/colstrom/quickstart"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Template-driven scaffolding."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<contracts>, [">= 0.13.0", "~> 0.13"])
      s.add_runtime_dependency(%q<erubis>, [">= 2.7.0", "~> 2.7"])
      s.add_runtime_dependency(%q<escort>, [">= 0.4.0", "~> 0.4"])
      s.add_runtime_dependency(%q<tilt>, [">= 2.0.2", "~> 2.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.10"])
      s.add_development_dependency(%q<flog>, ["~> 4.3"])
      s.add_development_dependency(%q<inch>, ["~> 0.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<reek>, ["~> 3.7"])
      s.add_development_dependency(%q<roodi>, ["~> 5.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.4"])
      s.add_development_dependency(%q<rubocop>, ["~> 0.35"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
    else
      s.add_dependency(%q<contracts>, [">= 0.13.0", "~> 0.13"])
      s.add_dependency(%q<erubis>, [">= 2.7.0", "~> 2.7"])
      s.add_dependency(%q<escort>, [">= 0.4.0", "~> 0.4"])
      s.add_dependency(%q<tilt>, [">= 2.0.2", "~> 2.0"])
      s.add_dependency(%q<bundler>, ["~> 1.10"])
      s.add_dependency(%q<flog>, ["~> 4.3"])
      s.add_dependency(%q<inch>, ["~> 0.7"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<reek>, ["~> 3.7"])
      s.add_dependency(%q<roodi>, ["~> 5.0"])
      s.add_dependency(%q<rspec>, ["~> 3.4"])
      s.add_dependency(%q<rubocop>, ["~> 0.35"])
      s.add_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
    end
  else
    s.add_dependency(%q<contracts>, [">= 0.13.0", "~> 0.13"])
    s.add_dependency(%q<erubis>, [">= 2.7.0", "~> 2.7"])
    s.add_dependency(%q<escort>, [">= 0.4.0", "~> 0.4"])
    s.add_dependency(%q<tilt>, [">= 2.0.2", "~> 2.0"])
    s.add_dependency(%q<bundler>, ["~> 1.10"])
    s.add_dependency(%q<flog>, ["~> 4.3"])
    s.add_dependency(%q<inch>, ["~> 0.7"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<reek>, ["~> 3.7"])
    s.add_dependency(%q<roodi>, ["~> 5.0"])
    s.add_dependency(%q<rspec>, ["~> 3.4"])
    s.add_dependency(%q<rubocop>, ["~> 0.35"])
    s.add_dependency(%q<simplecov>, ["~> 0.11"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
  end
end

